name:                hs-craft-solver
version:             0.1.0.0
github:              "githubuser/hs-craft-solver"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-craft-solver#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- http-conduit
- containers
- bytestring
- text
- vector
- tuple
- foundation
- ansi-terminal
- split
- async
- deepseq
- deepseq-generics
- strict-concurrency
- parallel
- cached-json-file
- utf8-string
- strict-io

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O3

library:
  source-dirs: src

executables:
  hs-craft-solver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-craft-solver

tests:
  hs-craft-solver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-craft-solver
